[package]
name = "c2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c3 = { path = "../c3" }

[features]
c1_some_feature = ["c3/c1_some_feature"]
